AWSTemplateFormatVersion: 2010-09-09
Description: |
  This template creates an ECS cluster.

Resources:
  clusterdemo2:
    Type: AWS::ECS::Cluster
    Properties:
      CapacityProviders: 
        - "FARGATE"
        - "FARGATE_SPOT"
      ClusterName: "demo2"

