AWSTemplateFormatVersion: 2010-09-09
Description: |
  
Parameters:
  
Resources:
  alb-2:
    Type: AWS::ElasticLoadBalancing::LoadBalancer
    Properties:
      AvailabilityZones: 
        - "eu-north-1a"
        - "eu-north-1b"
      HealthCheck:
        HealthyThreshold: "2"
        Interval: "5"
        Target: "http:8080/health"
        Timeout: "2"
        UnhealthyThreshold: "2"
      Instances: 
        - "String"
      LBCookieStickinessPolicy: 
        - CookieExpirationPeriod: "String"
          PolicyName: "String"
      Listeners: # Required
        - InstancePort: "8080"
          InstanceProtocol: "http"
          LoadBalancerPort: "8080"
          Protocol: "http"
      LoadBalancerName: "alb-2"
      Type: "application"
      Scheme: "internet-facing"
      SecurityGroups: 
        - "sg-092315a6345def03e"
        - "sg-0ce55b13a80757a16"
      Subnets: 
        - "subnet-0a83f151aa17679b3"
        - "subnet-043af4934a37aaf5a"
  TargetGroup2:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckEnabled: true
      HealthCheckIntervalSeconds: "5"
      HealthCheckPath: "/health"
      HealthCheckPort: "8080"
      HealthCheckProtocol: "http"
      HealthCheckTimeoutSeconds: "2"
      HealthyThresholdCount: "2"
      IpAddressType: "ipv4"
      Matcher:
        HttpCode: "200"
      Name: "targetgroup2"
      Port: "8080"
      Protocol: "http"
      TargetType: "ip"
      Targets: 
        - AvailabilityZone: "String"
          Id: "String"
          Port: "Number"
      UnhealthyThresholdCount: "Number"
      VpcId: "String"