---
Metadata:
  AWSToolsMetrics:
    IaC_Generator: "arn:aws:cloudformation:eu-north-1:248189902862:generatedTemplate/9bb8d460-7d7d-426c-98a9-43a9b231b6b3"
Resources:
  SQSQueue00StandardQueue00Jnstp:
    UpdateReplacePolicy: "Retain"
    Type: "AWS::SQS::Queue"
    DeletionPolicy: "Retain"
    Properties:
      SqsManagedSseEnabled: true
      ReceiveMessageWaitTimeSeconds: 0
      DelaySeconds: 0
      MessageRetentionPeriod: 345600
      MaximumMessageSize: 262144
      VisibilityTimeout: 30
      QueueName: "StandardQueue"
      Tags:
      - Value: "queue"
        Key: "exam"
